version: '3.8'

services:
## Frontend Service
  ui:
    build: 
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - be
    develop:
      watch:
        - path: ui/package.json
          action: rebuild
        - path: ./ui/next.config.js
          action: rebuild
        - path: ./ui
          target: /app
          action: sync

## Backend Service
  be:
    build: 
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql-db
    develop:
      watch:
        - path: be/package.json
          action: rebuild
        - path: ./be
          target: /app
          action: sync
    environment:
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MONGODB_URI: ${MONGODB_URI}

## Database Service
  mysql-db:
    image: mysql:8.3.0
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - meee:/data/mysql

  ## MongoDB Service
  mongo-db:
    image: mongo:latest
    volumes:
      - meee:/data/mongo
    environment:
      MONGO_INITDB_DATABASE: meee
    ports:
      - 27018:27017

volumes:
  meee:      