import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ApolloProvider from '@/lib/graphql/ApolloProvider';
import StoreProvider from '@/lib/redux/StoreProvider';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Foodie: Welcome to Foodie!',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  info,
  rate,
}: Readonly<{
  children: React.ReactNode;
  info: React.ReactNode;
  rate: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <StoreProvider>
        <ApolloProvider>
          <body className={inter.className}>
            {children}
            {info}
            {rate}
            <footer className='p-6 bg-gray-200 mt-8'>
              <Footer />
            </footer>
          </body>
        </ApolloProvider>
      </StoreProvider>
    </html>
  );
}
