import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ApolloProvider from '@/lib/graphql/ApolloProvider';
import StoreProvider from '@/lib/redux/StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Foodie: Welcome to Foodie!',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <StoreProvider>
        <ApolloProvider>
          <body className={inter.className}>{children}</body>
        </ApolloProvider>
      </StoreProvider>
    </html>
  );
}
